const data = {
  products: [
    {
      title: "Muskmelon",
      description: "Delicious and nutritious muskmelon.",
      category: "fruits",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1A",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/Muskmelon.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Watermelon",
      description: "Delicious and refreshing watermelon.",
      category: "fruits",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1B",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/Watermelon.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Papaya",
      description: "Delicious and nutritious papaya.",
      category: "fruits",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1C",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/papaya.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Pumpkin",
      description: "Delicious and nutritious pumpkin.",
      category: "fruits",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1D",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/Pumpkin.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Papaya Pearl",
      description: "Delicious and nutritious papaya pearl.",
      category: "fruits",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1E",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/papaiya-pearl.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Watermelon Madhurak",
      description: "Delicious and refreshing watermelon Madhurak.",
      category: "fruits",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1F",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Fruits/watermelon-madhurak.png"],
      vendor: '66cc1fd7e01566346667996f'
    },

    // Flower category
    {
      title: "Brezza Yellow",
      description: "Beautiful Brezza Yellow flowers.",
      category: "flowers",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1G",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Flowers/BREZZA-YELLOW.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Marigold Yellow",
      description: "Beautiful Marigold Yellow flowers.",
      category: "flowers",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1H",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Flowers/marigold-yellow.jpeg"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Sunflower Bhaskar",
      description: "Beautiful Sunflower Bhaskar flowers.",
      category: "flowers",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1I",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Flowers/sunflower-bhaskar.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Marigold Orange",
      description: "Beautiful Marigold Orange flowers.",
      category: "flowers",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1J",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Flowers/MARIGOLD-ORANGE.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Marigold",
      description: "Beautiful Marigold flowers.",
      category: "flowers",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1K",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Flowers/marigold.jpeg"],
      vendor: '66cc1fd7e01566346667996f'
    },

    // Vegetable category
    {
      title: "Broccoli",
      description: "Fresh and nutritious broccoli.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1L",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/BROCKKELY.jpeg"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Cherry Tomato",
      description: "Fresh and juicy cherry tomatoes.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1M",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Cherry-Tomato.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Radish",
      description: "Fresh and crunchy radishes.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1N",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Radish.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Carrot",
      description: "Fresh and crunchy carrots.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1O",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/carrot.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Bottle Gourd",
      description: "Fresh and nutritious bottle gourd.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1P",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Bottle-gourd.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Capsicum Green",
      description: "Fresh and spicy green chilies.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1Q",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/capsicum-Green.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Tomato Rasika",
      description: "Fresh and juicy Tomato Rasika.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1R",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Tomato-Rasika.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Cauliflower",
      description: "Fresh and nutritious cauliflower.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1S",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/cauliflower.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Brinjal Round",
      description: "Fresh and nutritious round brinjal.",
      category: "vegetables",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1T",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Brinjal-Round.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Capsicum Red",
      description: "Fresh red Capsicum.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1U",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/capsicum-red.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Onion",
      description: "Fresh and juicy onions.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1V",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/onion.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Cucumber",
      description: "Fresh and nutritious cucumber.",
      category: "vegetables",
      isFeatured: true,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1W",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/cucumber.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Beetroot",
      description: "Fresh and nutritious beetroot.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1X",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/beetroot.png"],
      vendor: '66cc1fd7e01566346667996f'
    },
    {
      title: "Yellow Capsicum",
      description: "Fresh and nutritious capsicum.",
      category: "vegetables",
      isFeatured: false,
      price: 9.99,
      rating: 4.94,
      stock: 5,
      sku: "RCH45Q1Y",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      images: ["/images/Vegetables/Capsicum-yellow.png"],
      vendor: '66cc1fd7e01566346667996f'
    },

  ],
};
export default data